---
version: "3.8"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    privileged: true
    tty: true
    stdin_open: true
    user: "0"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD=Ww12345 #optional
#       - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=root #optional
#       - SUDO_PASSWORD_HASH= #optional
#       - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/home #optional
    volumes:
      - /Ex/appdata/config:/config
    ports:
      - 80:8443
    restart: unless-stopped
    security_opt:
      - no-new-privileges:false
